# Generated by Django 2.2.4 on 2019-08-09 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='help',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
