# Generated by Django 2.2.4 on 2019-08-15 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20190815_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Pet',
        ),
    ]
