# Generated by Django 2.2.4 on 2019-08-15 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190815_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='created_date',
        ),
        migrations.AddField(
            model_name='pet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='begin_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 8, 15, 22, 5, 49, 591142, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='cidade',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='imagem',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
