# Generated by Django 2.2.4 on 2019-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190815_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
